version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secure_password #user: root password
      MYSQL_DATABASE: mydb  #db name
      MYSQL_USER: myuser  #user: myuser
      MYSQL_PASSWORD: password #user: myuser password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
